### ISSUE TITLE
Slides are not shown correctly

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/workshop-r-swe-rinpharma-2024#2]
When in https://openpharma.github.io/workshop-r-swe-rinpharma-2024/listing.html then clicking
on Introduction leads to a blog style page instead of a slidedeck. It seems to only work correctly for R Packages.
@shajoezhu did we change anything in this direction? e.g. yaml headers or so?

**Comment by shajoezhu** [comment]
hi daniel, now works

**Comment by danielinteractive** [comment]
super thanks @shajoezhu !!
